# Generated by Django 5.0.3 on 2024-04-17 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 17, 47, 40, 801501)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
