# Generated by Django 5.0.3 on 2024-04-17 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_otp_expiration_time_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 12, 21, 48, 683941, tzinfo=datetime.timezone.utc)),
        ),
    ]
