# Generated by Django 5.0.3 on 2024-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_nName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=100)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
