# Generated by Django 5.0.3 on 2024-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
