# Generated by Django 5.0.3 on 2024-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_contactpage_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Feedback', models.TextField(max_length=300)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Message',
            field=models.TextField(max_length=300),
        ),
    ]
