# Generated by Django 5.0.3 on 2024-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_feedbackpage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpage',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
