# Generated by Django 5.0.3 on 2024-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('institute_name', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('qulification', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
